# Staging Environment Configuration
# This file overrides default.yaml settings for staging environment

app:
  debug: false
  environment: "staging"

api:
  port: 3001
  timeout: 45000
  retries: 5
  cors:
    origins:
      - "https://staging.example.com"
      - "https://staging-api.example.com"
  rateLimit:
    max: 200

engines:
  playwright:
    headless: true
    timeout: 45000
    retries: 2
    options:
      slowMo: 0
      devtools: false
      trace: "on"
      screenshot: "only-on-failure"
      video: "retain-on-failure"

  jest:
    timeout: 15000
    retries: 3
    coverage: true
    watch: false

  k6:
    vus: 20
    duration: "60s"
    timeout: 90000
    stages:
      - duration: "20s"
        target: 10
      - duration: "40s"
        target: 20
      - duration: "20s"
        target: 0

  zap:
    timeout: 180000
    retries: 2

healing:
  confidenceThreshold: 0.7
  maxRetries: 3
  strategies:
    selectorHealing: true
    waitHealing: true
    assertionHealing: true
    navigationHealing: true
  fallbackStrategies:
    id: true
    css: true
    xpath: true
    neighbor: true

observability:
  logging:
    level: "info"
    format: "json"
    file: "./logs/staging-test-harness.log"
  metrics:
    enabled: true
    interval: 10000
  tracing:
    enabled: true
    endpoint: "http://jaeger-staging:14268"

database:
  enabled: true
  type: "postgresql"
  connection:
    host: "staging-db.example.com"
    port: 5432
    database: "test_harness_staging"
    username: "test_harness"
    password: "${DB_PASSWORD}"
  migrations:
    enabled: true
    path: "./migrations"

security:
  enabled: true
  authentication:
    enabled: true
    type: "jwt"
    secret: "${JWT_SECRET}"
  encryption:
    enabled: true
    algorithm: "aes-256-gcm"
    key: "${ENCRYPTION_KEY}"

orchestration:
  parallel: true
  maxConcurrency: 10
  timeout: 600000  # 10 minutes
  retryPolicy:
    enabled: true
    maxRetries: 2
    backoffMultiplier: 2
  reporting:
    enabled: true
    formats:
      - "json"
      - "html"
    outputDir: "./reports/staging"
